// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVF5uH5XhoK5jMTmDjLDDmjA3Rrh68Gyg',
    appId: '1:387256025631:android:06a99c32ebcdaa971fcb2a',
    messagingSenderId: '387256025631',
    projectId: 'chatting-app-3a20b',
    storageBucket: 'chatting-app-3a20b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfrp5L3wOhpbhRSFqI5aM2YJT1hOh1Z0',
    appId: '1:387256025631:ios:d9fd40dde3be140a1fcb2a',
    messagingSenderId: '387256025631',
    projectId: 'chatting-app-3a20b',
    storageBucket: 'chatting-app-3a20b.firebasestorage.app',
    androidClientId: '387256025631-8jhs5ml9vgqaj50ro1m0bc8i4dl4eseb.apps.googleusercontent.com',
    iosClientId: '387256025631-5ql3mk8cin8lhno4djgma3avba00ruv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chApp',
  );
}
