// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Y_uFapBqjl5xr0DOSuRJA6vDTSPmj3I',
    appId: '1:613314793444:android:d46c56e70e4c123f05c1f1',
    messagingSenderId: '613314793444',
    projectId: 'chat-app-b8683',
    storageBucket: 'chat-app-b8683.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-9ePk9LPPZfHzzqo3FgbNVNyh-27FopY',
    appId: '1:613314793444:ios:5b7a82e62669712b05c1f1',
    messagingSenderId: '613314793444',
    projectId: 'chat-app-b8683',
    storageBucket: 'chat-app-b8683.firebasestorage.app',
    androidClientId: '613314793444-0dkirp1t971mn1geum73bjl2nf983a8s.apps.googleusercontent.com',
    iosClientId: '613314793444-un2dpbee1o6ol5q9macbhsrkbh1ml8ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
